affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 8
grid_eps: 1.0
grid_range:
- -1
- 1
k: 5
mult_arity: 2
sb_trainable: true
sp_trainable: true
state_id: 4
symbolic.funs_name.0:
- - '0'
  - gaussian
  - gaussian
  - gaussian
  - gaussian
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.1:
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
symbolic_enabled: true
width:
- - 8
  - 0
- - 4
  - 0
- - 5
  - 0
