affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 10
grid_eps: 1.0
grid_range:
- -1
- 1
k: 5
mult_arity: 2
sb_trainable: true
sp_trainable: true
state_id: 7
symbolic.funs_name.0:
- - '0'
  - x^2
  - x
  - x
  - x
  - x
  - x^2
  - x^2
- - '0'
  - x^2
  - x
  - x
  - x
  - x
  - '0'
  - sin
- - '0'
  - x^2
  - x
  - x
  - x
  - x
  - sqrt
  - '0'
symbolic.funs_name.1:
- - x
  - x
  - x
- - x
  - x
  - x
- - x
  - x
  - x
- - x
  - x
  - x
- - x
  - x
  - x
symbolic_enabled: true
width:
- - 8
  - 0
- - 3
  - 0
- - 5
  - 0
